const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Platform: 0},
	{Player: 0},
	{Solid: 0},
	{Sprite3: 0},
	{FloorWall: 0},
	{Sprite5: 0},
	{Ship: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Fuel: 0},
	{DoubleJump: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Button: 0},
	{Sprite13: 0},
	{Text: 0},
	{idontknow: 0},
	{MoveTo: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Keyboard: 0},
	{BeginGame: 0},
	{AJAX: 0},
	{OtherGames: 0},
	{Browser: 0},
	{Title: 0},
	{CollectFuel: 0},
	{GotFuel: 0},
	{timeLeft: 0},
	{layout: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	FloorWall: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Ship: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Fuel: class extends self.ISpriteInstance {},
	DoubleJump: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	idontknow: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	BeginGame: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	OtherGames: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	Title: class extends self.ITextInstance {},
	CollectFuel: class extends self.ITextInstance {}
}